{% set name = "WTForms-JSON" %}
{% set version = "0.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 27fde015d2d0642732da7ba304e6d17aea2744f79d7a9f963f9f47045a35ff6d

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - wtforms >=1.0.5
    - six >=1.3.0

test:
  imports:
    - wtforms_json

about:
  home: https://github.com/kvesteri/wtforms-json
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Adds smart json support for WTForms. Useful for when using WTForms with RESTful APIs.

  doc_url: http://wtforms-json.readthedocs.org/
  dev_url: https://github.com/kvesteri/wtforms-json

extra:
  recipe-maintainers:
    - sodre
